sudo: false
language: python
cache: pip
dist: trusty

python:
  - "3.6.4"

install:
  - sudo apt-get install xdotool
  - pip install pipenv
  - pipenv install --dev
  - pipenv install codecov --dev

before_script:
    # Headless testing in travis ci: https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"

script:
  - xvfb-run pipenv run pytest

after_success: pipenv run codecov
